-- Demo seed data for careers module
-- Safe to re-run: it removes previous demo rows and inserts fresh ones.

BEGIN;

-- Remove previous demo applicant rows first (FK references jobs)
DELETE FROM public.job_applications
WHERE email LIKE '%@demo.techneth.local'
   OR job_title_snapshot LIKE '[DEMO]%';

-- Remove previous demo jobs
DELETE FROM public.jobs
WHERE title LIKE '[DEMO]%';

-- Insert demo jobs
INSERT INTO public.jobs (
  title,
  department,
  location,
  employment_type,
  experience_level,
  description,
  requirements,
  responsibilities,
  benefits,
  salary_range,
  is_remote,
  is_active,
  application_deadline,
  created_by,
  created_at,
  updated_at
) VALUES
(
  '[DEMO] Full Stack Engineer',
  'Engineering',
  'Amsterdam',
  'full-time',
  'mid',
  'Build and maintain web applications across frontend and backend.',
  ARRAY['3+ years experience', 'React/Next.js', 'Node.js', 'PostgreSQL'],
  ARRAY['Develop product features', 'Collaborate with design and product', 'Review code and improve quality'],
  ARRAY['Health insurance', 'Remote flexibility', 'Learning budget'],
  'EUR 55,000 - 75,000',
  true,
  true,
  CURRENT_DATE + INTERVAL '30 days',
  NULL,
  NOW(),
  NOW()
),
(
  '[DEMO] UI/UX Designer',
  'Design',
  'Rotterdam',
  'full-time',
  'senior',
  'Design intuitive digital products and improve design system consistency.',
  ARRAY['5+ years experience', 'Figma', 'Design systems', 'Usability testing'],
  ARRAY['Create high-fidelity prototypes', 'Conduct user research', 'Work with engineering on implementation'],
  ARRAY['Flexible hours', 'Home office setup', 'Conference budget'],
  'EUR 50,000 - 70,000',
  true,
  true,
  CURRENT_DATE + INTERVAL '45 days',
  NULL,
  NOW(),
  NOW()
),
(
  '[DEMO] DevOps Engineer',
  'Infrastructure',
  'Utrecht',
  'contract',
  'lead',
  'Improve CI/CD, observability, and reliability of cloud infrastructure.',
  ARRAY['AWS/GCP', 'Kubernetes', 'Terraform', 'Monitoring stack'],
  ARRAY['Automate deployments', 'Improve system reliability', 'Set up scalable infrastructure'],
  ARRAY['Competitive rate', 'Hybrid work', 'Long-term project'],
  'EUR 70 - 95 / hour',
  false,
  true,
  CURRENT_DATE + INTERVAL '20 days',
  NULL,
  NOW(),
  NOW()
);

-- Insert demo applications linked to demo jobs
INSERT INTO public.job_applications (
  job_id,
  job_title_snapshot,
  full_name,
  email,
  phone,
  experience,
  expected_salary,
  linkedin,
  portfolio,
  additional_info,
  resume_file_name,
  resume_file_path,
  resume_file_url,
  cover_letter_file_name,
  cover_letter_file_path,
  cover_letter_file_url,
  status,
  status_notes,
  last_emailed_at,
  communication_history,
  created_at,
  updated_at
) VALUES
(
  (SELECT id FROM public.jobs WHERE title = '[DEMO] Full Stack Engineer' LIMIT 1),
  '[DEMO] Full Stack Engineer',
  'Alice de Vries',
  'alice.dev@demo.techneth.local',
  '+31 6 1010 1010',
  '4 years in web development with React and Node.js.',
  'EUR 62,000',
  'https://linkedin.com/in/alice-devries-demo',
  'https://portfolio.alice-demo.local',
  'Interested in backend-heavy responsibilities and mentoring juniors.',
  'alice_resume.pdf',
  'demo/fullstack/alice_resume.pdf',
  'https://example.com/demo/alice_resume.pdf',
  'alice_cover_letter.pdf',
  'demo/fullstack/alice_cover_letter.pdf',
  'https://example.com/demo/alice_cover_letter.pdf',
  'new',
  NULL,
  NULL,
  '[]'::jsonb,
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
),
(
  (SELECT id FROM public.jobs WHERE title = '[DEMO] Full Stack Engineer' LIMIT 1),
  '[DEMO] Full Stack Engineer',
  'Bilal Khan',
  'bilal.khan@demo.techneth.local',
  '+31 6 2020 2020',
  '6 years with TypeScript, distributed systems, and API design.',
  'EUR 72,000',
  'https://linkedin.com/in/bilal-khan-demo',
  'https://bilal-demo.local',
  'Open to relocation and can start in one month.',
  'bilal_resume.pdf',
  'demo/fullstack/bilal_resume.pdf',
  'https://example.com/demo/bilal_resume.pdf',
  NULL,
  NULL,
  NULL,
  'reviewing',
  'Strong backend profile, pending technical interview.',
  NOW() - INTERVAL '1 day',
  '[{"sent_at":"2026-04-05T10:00:00Z","sent_by":"Demo Admin","subject":"Application update","body":"Thanks for applying.","mode":"individual"}]'::jsonb,
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '1 day'
),
(
  (SELECT id FROM public.jobs WHERE title = '[DEMO] Full Stack Engineer' LIMIT 1),
  '[DEMO] Full Stack Engineer',
  'Carla Mendez',
  'carla.mendez@demo.techneth.local',
  '+31 6 3030 3030',
  '5 years in full stack SaaS products.',
  'EUR 68,000',
  'https://linkedin.com/in/carla-mendez-demo',
  'https://carla-demo.local',
  'Particularly interested in product-focused teams.',
  'carla_resume.pdf',
  'demo/fullstack/carla_resume.pdf',
  'https://example.com/demo/carla_resume.pdf',
  'carla_cover_letter.pdf',
  'demo/fullstack/carla_cover_letter.pdf',
  'https://example.com/demo/carla_cover_letter.pdf',
  'shortlisted',
  'Great culture fit and strong communication.',
  NOW() - INTERVAL '6 hours',
  '[{"sent_at":"2026-04-06T08:30:00Z","sent_by":"Demo Admin","subject":"Shortlist update","body":"You are shortlisted.","mode":"individual"}]'::jsonb,
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '6 hours'
),
(
  (SELECT id FROM public.jobs WHERE title = '[DEMO] UI/UX Designer' LIMIT 1),
  '[DEMO] UI/UX Designer',
  'Daan Visser',
  'daan.visser@demo.techneth.local',
  '+31 6 4040 4040',
  '7 years in product design and design systems.',
  'EUR 64,000',
  'https://linkedin.com/in/daan-visser-demo',
  'https://dribbble.com/daan-demo',
  'Can share case studies on enterprise dashboard redesign.',
  'daan_resume.pdf',
  'demo/design/daan_resume.pdf',
  'https://example.com/demo/daan_resume.pdf',
  NULL,
  NULL,
  NULL,
  'new',
  NULL,
  NULL,
  '[]'::jsonb,
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
),
(
  (SELECT id FROM public.jobs WHERE title = '[DEMO] UI/UX Designer' LIMIT 1),
  '[DEMO] UI/UX Designer',
  'Eva Noor',
  'eva.noor@demo.techneth.local',
  '+31 6 5050 5050',
  '4 years in UX research and prototyping.',
  'EUR 58,000',
  'https://linkedin.com/in/eva-noor-demo',
  'https://behance.net/eva-noor-demo',
  'Comfortable running discovery workshops with stakeholders.',
  'eva_resume.pdf',
  'demo/design/eva_resume.pdf',
  'https://example.com/demo/eva_resume.pdf',
  'eva_cover_letter.pdf',
  'demo/design/eva_cover_letter.pdf',
  'https://example.com/demo/eva_cover_letter.pdf',
  'rejected',
  'Good profile but less aligned with seniority requirement.',
  NOW() - INTERVAL '12 hours',
  '[{"sent_at":"2026-04-06T05:00:00Z","sent_by":"Demo Admin","subject":"Application outcome","body":"Thank you for your time.","mode":"individual"}]'::jsonb,
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '12 hours'
),
(
  (SELECT id FROM public.jobs WHERE title = '[DEMO] DevOps Engineer' LIMIT 1),
  '[DEMO] DevOps Engineer',
  'Farid Soltani',
  'farid.soltani@demo.techneth.local',
  '+31 6 6060 6060',
  '9 years in cloud infrastructure and SRE.',
  'EUR 90/hour',
  'https://linkedin.com/in/farid-soltani-demo',
  'https://farid-demo.local',
  'Available for immediate contract start.',
  'farid_resume.pdf',
  'demo/devops/farid_resume.pdf',
  'https://example.com/demo/farid_resume.pdf',
  NULL,
  NULL,
  NULL,
  'reviewing',
  'Technical stack is promising, checking references.',
  NOW() - INTERVAL '4 hours',
  '[{"sent_at":"2026-04-06T09:00:00Z","sent_by":"Demo Admin","subject":"Next steps","body":"We are reviewing your profile.","mode":"bulk"}]'::jsonb,
  NOW() - INTERVAL '4 days',
  NOW() - INTERVAL '4 hours'
),
(
  (SELECT id FROM public.jobs WHERE title = '[DEMO] DevOps Engineer' LIMIT 1),
  '[DEMO] DevOps Engineer',
  'Gita Sharma',
  'gita.sharma@demo.techneth.local',
  '+31 6 7070 7070',
  '10 years in platform engineering and CI/CD architecture.',
  'EUR 95/hour',
  'https://linkedin.com/in/gita-sharma-demo',
  'https://gita-demo.local',
  'Has led migration from monolith infra to Kubernetes.',
  'gita_resume.pdf',
  'demo/devops/gita_resume.pdf',
  'https://example.com/demo/gita_resume.pdf',
  'gita_cover_letter.pdf',
  'demo/devops/gita_cover_letter.pdf',
  'https://example.com/demo/gita_cover_letter.pdf',
  'hired',
  'Offer accepted and onboarding scheduled.',
  NOW() - INTERVAL '1 hour',
  '[{"sent_at":"2026-04-06T11:00:00Z","sent_by":"Demo Admin","subject":"Offer confirmation","body":"Welcome aboard.","mode":"individual"}]'::jsonb,
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '1 hour'
);

COMMIT;
